name: Deploy Dev
on:
  push:
    branches:
      - feature/*
  
jobs:
  Lint:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Check nodejs version
        run: node -v

      - name: Check npm version
        run: npm -v

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run lint
  UnitTest:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Lint
        run: npm run test:unit
  DeployDevelop:
    runs-on: ubuntu-24.04
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install

      - name: Build
        run: npm run build  # Vue ビルド

      - name: Deploy  # S3にデプロイ 
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev
#        run: |
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.br" --content-encoding br --content-type "application/javascript"
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.css" --content-encoding br --content-type "text/css"
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.html" --content-encoding br --content-type "text/html"
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.ico" --content-encoding br --content-type "image/x-icon"
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.js" --content-encoding br --content-type "application/javascript"
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.json" --content-encoding br --content-type "application/json"
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.png" --content-encoding br --content-type "image/png"
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.svg" --content-encoding br --content-type "image/svg+xml"
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.woff" --content-encoding br --content-type "font/woff"
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.woff2" --content-encoding br --content-type "font/woff2"
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.ttf" --content-encoding br --content-type "font/ttf"
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.eot" --content-encoding br --content-type "font/eot"
#          aws s3 cp --recursive --region ap-northeast-1 dist s3://coccole-content-dev --recursive --exclude "*" --include "*.map" --content-encoding br --content-type "application/json"
                    
      - name: Invalidation  # CF Invalidation
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ap-northeast-1
        run:
          aws cloudfront create-invalidation --distribution-id E3B1AU20ZIZCDY --paths "/*"

